//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string NameContact { get; set; }
        public string ValContact { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
